version: '3.1'
volumes:
  chat-data:

services:
  fhirpath:
    build: ./fhirpath
    volumes:
      - ./fhirpath:/usr/src/app
    ports:
      - "8081:8080"
  backend:
    build: ./backend
    command: ["wait-for-it.sh", "devbox:8080", "--strict", "--timeout=0", "--", "adev", "runserver"]
    depends_on:
      - devbox
    links:
      - devbox
    env_file:
      - .env
    volumes:
      - ./backend:/app:cached
      - ./config:/var/config:cached
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh:cached
  devbox:
    image: "healthsamurai/devbox:0.4.7"
    command: ["wait-for-it.sh", "database:5432", "--strict", "--timeout=0", "--", "java", "-jar", "/aidbox.jar", "-m", "devbox.core"]
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh:cached
      - ./config:/var/config:cached
  devbox-db:
    image: "aidbox/db:11.4.0.2"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
